### ISSUE TITLE
Name of the GCAM scenario

### ISSUE THREAD

**Issue by nanhung** [JGCRI/rfasst#69]
The name of the GCAM scenario `scen_name` can not arbitrary define in `m1_emissions_rescale()` . Here is my code ,

```r
data.wd <- system.file("extdata", package="rfasst")

db_path <- data.wd
query_path <- data.wd
db_name <- "database_basexdb_5p3_release"
prj_name <- "testJOSS.dat" 
#scen_name<-"Reference_gcam5p3_release" 
scen_name<-"Ref_gcam5p3_release"  # cannot use the arbitrary name? 
queries<-"queries_rfasst.xml" 
```

I got the error output as,

![Screenshot from 2021-11-09 15-00-04](https://user-images.githubusercontent.com/25087463/141019275-bfbe9393-162e-4755-a27f-9cac0b5123db.png)

The error might come from `rgcam` package at this line

```r
prj <- rgcam::addScenario(conn, prj_name, scen_name, paste0(query_path, "/", queries), clobber = F)
```

**Comment by jonsampedro** [comment]
@nanhung the scenario name cannot be arbitrary, it has to be one of the scenarios of the database you are connecting with.  This is associated with the structure of the `rgcam` package, in which you create the connection with your scenario in two steps:

```conn <- localDBConn('/path/to/dbs', 'my-gcamdb_basexdb')``` When you run this, the console reports the scenarios on the DB you are connecting with.

```prj <- addScenario(conn, 'my-project-name.dat', 'my-scenario-name', 'my-batch-queries.xml')``` In this step, you add the scenario you want to the project. 

- `my-project-name.dat` can be an arbitrary name to save the project in your directory, so that in a next time you only need to `prj<-loadProject("my-project-name.dat")` 
-  `my-scenario-name` is the name of the scenario and should be exactly as it is on the DB you have made the connection with.
- `my-batch-queries.xml` is the query file (+query path if needed) you are using in the analysis (`queries_rfasst`).

I will clarfity this issue on the dicumentation vignettes.

**Comment by nanhung** [comment]
Thanks! It will be easy for the user if they do not need to assign the `my-scenario-name` since it has a certain naming rule to follow.

**Comment by jonsampedro** [comment]
Thanks @nanhung ! Just to clarify, each GCAM simulation has an associated name that will be user defined (no naming rule), so that's why rgcam is structured like that.
